// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gonzalez_BankApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250618095515_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Gonzalez_BankApp.Models.Entities.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("Gonzalez_BankApp.Models.Entities.CreditCard", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AvailCredit")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpDate")
                        .HasColumnType("TEXT");

                    b.HasKey("CardId");

                    b.ToTable("CreditCard", (string)null);
                });

            modelBuilder.Entity("Gonzalez_BankApp.Models.Entities.Customer", b =>
                {
                    b.Property<int>("CustId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CreditScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CustId");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("Gonzalez_BankApp.Models.Entities.CustomerAccount", b =>
                {
                    b.Property<int>("CustId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CustId", "AccountId");

                    b.HasIndex("AccountId");

                    b.ToTable("CustomerAccount", (string)null);
                });

            modelBuilder.Entity("Gonzalez_BankApp.Models.Entities.CustomerCreditCard", b =>
                {
                    b.Property<int>("CustId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CustId", "CardId");

                    b.HasIndex("CardId");

                    b.ToTable("CustomerCreditCard", (string)null);
                });

            modelBuilder.Entity("Gonzalez_BankApp.Models.Entities.CustomerAccount", b =>
                {
                    b.HasOne("Gonzalez_BankApp.Models.Entities.Account", "Account")
                        .WithMany("CustomerAccounts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gonzalez_BankApp.Models.Entities.Customer", "Customer")
                        .WithMany("CustomerAccounts")
                        .HasForeignKey("CustId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Gonzalez_BankApp.Models.Entities.CustomerCreditCard", b =>
                {
                    b.HasOne("Gonzalez_BankApp.Models.Entities.CreditCard", "CreditCard")
                        .WithMany("CustomerCreditCards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gonzalez_BankApp.Models.Entities.Customer", "Customer")
                        .WithMany("CustomerCreditCards")
                        .HasForeignKey("CustId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditCard");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Gonzalez_BankApp.Models.Entities.Account", b =>
                {
                    b.Navigation("CustomerAccounts");
                });

            modelBuilder.Entity("Gonzalez_BankApp.Models.Entities.CreditCard", b =>
                {
                    b.Navigation("CustomerCreditCards");
                });

            modelBuilder.Entity("Gonzalez_BankApp.Models.Entities.Customer", b =>
                {
                    b.Navigation("CustomerAccounts");

                    b.Navigation("CustomerCreditCards");
                });
#pragma warning restore 612, 618
        }
    }
}
